# EDA

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## 1. Data Import

In [4]:
df_solar = pd.read_csv('Data/SEMS_data.csv')
df_solar.head()

,Datum,Elektrárna,Klasifikace,Kapacita(kW),PV(kWh),Prodej(kWh),Koupit(kWh),Spotřeba(kWh),Spotřebováno v domácnosti(kWh),Vlastní poměr(%),Contribution Ratio(%),Příjem(CZK)
0,01.01.2024,HFVE Zapletal Simon,Úložiště baterie,7.6,1.2,0.11,14.12,20.01,5.89,98.17,29.44,6.0
1,02.01.2024,HFVE Zapletal Simon,Úložiště baterie,7.6,1.3,0.11,6.32,12.21,5.89,98.17,48.24,6.5
2,03.01.2024,HFVE Zapletal Simon,Úložiště baterie,7.6,1.9,0.12,5.51,12.19,6.68,98.24,54.80,9.5
3,04.01.2024,HFVE Zapletal Simon,Úložiště baterie,7.6,1.8,0.15,6.13,11.78,5.65,97.41,47.96,9.0
4,05.01.2024,HFVE Zapletal Simon,Úložiště baterie,7.6,4.5,0.88,5.14,14.76,9.62,91.62,65.18,22.5

In [6]:
df_weather = pd.read_csv('Data/weather.csv')
df_weather.head()

,Unnamed: 0,datetime,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,...,normal.tempmax,normal.tempmin,normal.feelslike,normal.precip,normal.humidity,normal.snowdepth,normal.windspeed,normal.windgust,normal.winddir,normal.cloudcover
0,0,2023-09-01,18.1,9.5,14.3,18.1,8.3,14.2,10.4,77.7,...,"[11.5, 19.2, 31.5]","[6.9, 10.6, 16.2]","[4.8, 19.2, 30.5]","[0.0, 7.7, 43.7]","[54.4, 78.2, 97.2]","[0.0, 0.0, 0.0]","[11.9, 21.2, 29.5]","[39.6, 55.1, 111.6]","[30.3, 182.8, 327.7]","[4.7, 62.4, 100.0]"
1,1,2023-09-02,21.3,15.0,17.7,21.3,15.0,17.7,14.2,81.1,...,"[12.3, 18.5, 23.6]","[6.3, 10.4, 14.8]","[3.0, 18.5, 23.6]","[0.0, 4.0, 24.9]","[61.4, 78.0, 96.6]","[0.0, 0.0, 0.0]","[9.4, 19.1, 29.9]","[39.6, 55.1, 75.6]","[28.5, 176.3, 288.1]","[7.4, 63.7, 99.5]"
2,2,2023-09-03,19.2,14.3,16.3,19.2,14.3,16.3,12.6,79.9,...,"[11.0, 19.5, 25.8]","[5.7, 10.4, 15.2]","[3.2, 19.5, 25.8]","[0.0, 2.7, 19.4]","[62.4, 76.6, 93.4]","[0.0, 0.0, 0.0]","[11.5, 20.9, 36.0]","[28.8, 58.3, 79.2]","[38.0, 175.5, 314.5]","[17.0, 60.1, 100.0]"
3,3,2023-09-04,18.5,11.9,14.7,18.5,11.9,14.7,9.9,73.9,...,"[11.1, 19.3, 26.3]","[6.3, 10.8, 16.2]","[2.8, 19.3, 26.3]","[0.0, 2.6, 13.5]","[65.4, 77.6, 92.8]","[0.0, 0.0, 0.0]","[10.8, 20.5, 36.7]","[39.6, 57.2, 90.0]","[43.3, 189.0, 288.3]","[8.3, 60.7, 100.0]"
4,4,2023-09-05,24.2,9.4,15.7,24.2,7.9,15.4,9.9,71.2,...,"[7.7, 19.4, 27.4]","[3.4, 10.6, 14.7]","[-3.5, 19.4, 27.2]","[0.0, 2.7, 32.1]","[66.7, 77.5, 91.3]","[0.0, 0.0, 0.0]","[9.0, 22.0, 50.4]","[43.2, 63.0, 100.8]","[33.8, 157.0, 269.7]","[21.0, 55.9, 94.3]"

## 1.2 Missing values